# Make sure not to name your pipeline deploy, as this will conflict with the built-in deploy action
name: deploy infra and app using a mix of bash and github actions
on:
  workflow_dispatch:
  push:
    branches:
      - DemoTestBranch
env:
  AZURE_WEBAPP_NAME: BewareTheAzure_Saqib_Dragon
  AZURE_APPSERVICE_PLAN: front-end-app-service-plan
  NODE_VERSION: "20.x"
jobs:
  validate-credentials:
    name: validate azure credentials
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main

      - name: Log in to Azure
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
# generate credentials using this command, then store them in GitHub secrets
# az ad sp create-for-rbac --name "pipelineCredentials" --role contributor --scopes /subscriptions/{subscription-id}/resourceGroups/{resource-group} 

      - name: logout
        run: |
          az logout

  build-infrastructure:
    name: build infrastructure
    needs: validate-credentials
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main

      - name: Log in to Azure
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
      
      - name: build infrastructure
        run: |
              az deployment group create \
                --resource-group 'IacReferenceForCodeAlong' \
                --template-file './infra/main.bicep' \
                --parameters '@./infra/main.parameters.json' \
                --parameters appName=${{env.AZURE_WEBAPP_NAME}} appServicePlanName=${{env.AZURE_APPSERVICE_PLAN}} 
  
  build-app:
    name: build react app
    needs: build-infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main

      - name: Use node.js ${{env.NODE_VERSION}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: npm install and build
        run: |
          cd code/ui/my-react-app 
          npm install
          npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: website
          path: code/ui/my-react-app/dist/

  deploy-app:
    name: deploy react app
    needs: build-app
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Azure
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: downloading artifact
        uses: actions/download-artifact@v4
        with:
          name: website
          path: website

      - name: zip files
        run: |
          cd website
          zip -r ../website.zip .
      
      - name: deploy to azure web app
        id: deploy-to-web-app
        run: |
          ls
          az webapp deployment source config-zip \
            --resource-group 'IacReferenceForCodeAlong' \
            --name ${{env.AZURE_WEBAPP_NAME}} \
            --src ./website.zip